// <auto-generated />
namespace DevOpsConf2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SponsorTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SponsorTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201602011816567_Sponsor-Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
